version: "3"
services:
  api:
    container_name: golang
    build:
      context: .
      dockerfile: app/Dockerfile
    tty: true
    command: "air -c .air.toml"
    ports:
      - "8080:8080"
    volumes:
      - ./app:/go/src/app