import Head from "next/head";
import { GeneratePDF } from "../components/GeneratePDF";
import styles from "../styles/Home.module.css";

export default function Home() {
  const data = [
    {
      firstname: "hirahara",
      lastname: "naoki",
      age: 23,
    },
  ];
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>Next JS Convert HTML to PDF</h1>
        <div>
          <ul>
            {data.map((item, i) => (
              <li key={i}>{item.lastname}</li>
            ))}
          </ul>
        </div>
        <GeneratePDF data={data} />
      </main>
    </div>
  );
}

// export async function getStaticProps() {
//   const res = await fetch("http://localhost:3000/api/people");
//   const people = await res.json();

//   return {
//     props: {
//       people,
//     },
//   };
// }
